package im.bci.newtonadv.platform.lwjgl.twl;

import java.util.ArrayList;
import java.util.List;

class JoypadPresetFactory {

	static List<JoypadPreset> create() {
		List<JoypadPreset> presets = new ArrayList<JoypadPreset>();
		JoypadPreset conf0 = new JoypadPreset();
		conf0.setName("Afterglow PS3 Controller");
		conf0.setxAxis(0);
		conf0.setyAxis(1);
		conf0.setKeyJump(0);
		conf0.setKeyRotateCounterClockWise(4);
		conf0.setKeyRotateClockwise(5);
		conf0.setKeyReturn(0);
		conf0.setKeyReturnToMenu(12);
		presets.add(conf0);
		JoypadPreset conf1 = new JoypadPreset();
		conf1.setName("Logitech Logitech RumblePad 2 USB Controllers");
		conf1.setxAxis(0);
		conf1.setyAxis(1);
		conf1.setKeyJump(0);
		conf1.setKeyRotateCounterClockWise(4);
		conf1.setKeyRotateClockwise(5);
		conf1.setKeyReturn(0);
		conf1.setKeyReturnToMenu(9);
		presets.add(conf1);
		JoypadPreset conf2 = new JoypadPreset();
		conf2.setName("Mega World USB Game Controllers");
		conf2.setxAxis(0);
		conf2.setyAxis(1);
		conf2.setKeyJump(0);
		conf2.setKeyRotateCounterClockWise(4);
		conf2.setKeyRotateClockwise(6);
		conf2.setKeyReturn(0);
		conf2.setKeyReturnToMenu(9);
		presets.add(conf2);
		JoypadPreset conf3 = new JoypadPreset();
		conf3.setName("SAITEK P220");
		conf3.setxAxis(0);
		conf3.setyAxis(1);
		conf3.setKeyJump(0);
		conf3.setKeyRotateCounterClockWise(6);
		conf3.setKeyRotateClockwise(7);
		conf3.setKeyReturn(0);
		conf3.setKeyReturnToMenu(4);
		presets.add(conf3);
		JoypadPreset conf4 = new JoypadPreset();
		conf4.setName("USB GAMEPAD 8116");
		conf4.setxAxis(0);
		conf4.setyAxis(1);
		conf4.setKeyJump(2);
		conf4.setKeyRotateCounterClockWise(4);
		conf4.setKeyRotateClockwise(5);
		conf4.setKeyReturn(2);
		conf4.setKeyReturnToMenu(9);
		presets.add(conf4);
		JoypadPreset conf5 = new JoypadPreset();
		conf5.setName("Mega World Thrustmaster dual analog 3.2");
		conf5.setxAxis(0);
		conf5.setyAxis(1);
		conf5.setKeyJump(1);
		conf5.setKeyRotateCounterClockWise(4);
		conf5.setKeyRotateClockwise(6);
		conf5.setKeyReturn(1);
		conf5.setKeyReturnToMenu(9);
		presets.add(conf5);
		JoypadPreset conf6 = new JoypadPreset();
		conf6.setName("Thrustmaster Run'N' Drive Wireless PS3");
		conf6.setxAxis(0);
		conf6.setyAxis(1);
		conf6.setKeyJump(0);
		conf6.setKeyRotateCounterClockWise(4);
		conf6.setKeyRotateClockwise(5);
		conf6.setKeyReturn(0);
		conf6.setKeyReturnToMenu(12);
		presets.add(conf6);
		JoypadPreset conf7 = new JoypadPreset();
		conf7.setName("Thrustmaster Run'N' Drive Wireless");
		conf7.setxAxis(0);
		conf7.setyAxis(1);
		conf7.setKeyJump(0);
		conf7.setKeyRotateCounterClockWise(4);
		conf7.setKeyRotateClockwise(5);
		conf7.setKeyReturn(0);
		conf7.setKeyReturnToMenu(9);
		presets.add(conf7);
		return presets;
	}
}
